version: '3.8'

services:
  app:
    build: .
    container_name: nuvio-streams-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=7000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - nuvio-network
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:7000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:alpine
    container_name: nuvio-streams-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - nuvio-network
    depends_on:
      - app

networks:
  nuvio-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
